spring.application.name=voluntplus

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.cors.allowed-origin=${FRONTEND_URL}
app.business-zone=${APP_BUSINESS_ZONE:America/Sao_Paulo}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URI}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
