CREATE TABLE IF NOT EXISTS service_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES user_accounts(id),
    name VARCHAR(255) NOT NULL,
    descricao VARCHAR(4000),
    modalities VARCHAR(255), id_categoria VARCHAR(255), status VARCHAR(255),
    provider_image TEXT, dia_da_semana VARCHAR(255), turno VARCHAR(255),
    cep VARCHAR(255), estado VARCHAR(255), cidade VARCHAR(255), bairro VARCHAR(255),
    tipo_localizacao VARCHAR(255),
    whatsapp VARCHAR(255), telefone VARCHAR(255), instagram VARCHAR(255), site VARCHAR(255),
    publication_date TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS service_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES service_listings(id),
    author_id BIGINT NOT NULL REFERENCES user_accounts(id),
    nota INTEGER NOT NULL CHECK (nota BETWEEN 1 AND 5),
    comentario VARCHAR(500) NOT NULL,
    data_criacao TIMESTAMPTZ
);
